stages:
  - copy
  - kill
  - build
  - deploy

copy-project:
  stage: copy

  tags:
    - buildopc

  script:
    - xcopy /s .\Datalake\Datalake "C:\app\Datalake" /K /D /H /Y

kill-previous:
  stage: kill

  tags:
    - buildopc

  when: on_success

  script:
    - taskkill /f /im Datalake.exe
  
  allow_failure: true

build-datalake:
  stage: build

  tags:
    - buildopc

  script:
    - cd C:\app\Datalake
    - msbuild /t:Restore
    - msbuild /t:Build /p:Configuration=Release

deploy-datalake:
  stage: deploy

  tags:
    - buildopc
    
  script:
    - sc start Datalake
