stages:
  - copy
  - kill
  - build
  - deploy

copy-project:
  stage: copy
  only: [tags]
  tags:
    - buildopc
  script:
    - xcopy /s .\Datalake\Datalake "C:\app\Datalake" /K /D /H /Y

kill-previous:
  stage: kill
  only: [tags]
  when: on_success
  allow_failure: true
  tags:
    - buildopc
  script:
    - taskkill /f /im Datalake.exe

build-datalake:
  stage: build
  only: [tags]
  tags:
    - buildopc
  script:
    - cd C:\app\Datalake
    - msbuild /t:Restore
    - msbuild /t:Build /p:Configuration=Release

deploy-datalake:
  stage: deploy
  only: [tags]
  tags:
    - buildopc
  script:
    - sc start Datalake