stages:
  - copy
  - build
  - deploy

copy-project:
  stage: copy

  tags:
    - buildopc

  script:
    - xcopy /s .\Datalake\Datalake "C:\app\Datalake" /K /D /H /Y

  only:
    - /^\d+.\d+.\d+$/

build-datalake:
  stage: build

  tags:
    - buildopc

  script:
    - cd C:\app\Datalake
    - msbuild /t:Restore
    - msbuild /t:Build /p:Configuration=Release

  only:
    - /^\d+.\d+.\d+$/

deploy-datalake:
  stage: deploy

  tags:
    - buildopc

  script:
    - tasklist | findstr /i "Datalake.exe" && taskkill /f /im Datalake.exe
    - cd C:\Dist\Datalake
    - Datalake.exe

  only:
    - /^\d+.\d+.\d+$/
