// <auto-generated />
using System;
using DatalakeDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatalakeDatabase.Migrations
{
    [DbContext(typeof(DatalakeEfContext))]
    [Migration("20240610100628_RemoveGlobalAccessTypeFromUsers")]
    partial class RemoveGlobalAccessTypeFromUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatalakeDatabase.Models.AccessRights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessType")
                        .HasColumnType("integer");

                    b.Property<int?>("BlockId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer");

                    b.Property<int?>("TagId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserGroupGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TagId");

                    b.HasIndex("UserGroupGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("AccessRights");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("GlobalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.BlockProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.ToTable("BlockProperties");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.BlockTag", b =>
                {
                    b.Property<int>("BlockId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Relation")
                        .HasColumnType("integer");

                    b.HasKey("BlockId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("BlockTags");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("RefId")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.Settings", b =>
                {
                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Formula")
                        .HasColumnType("text");

                    b.Property<Guid>("GlobalGuid")
                        .HasColumnType("uuid");

                    b.Property<short>("Interval")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsScaling")
                        .HasColumnType("boolean");

                    b.Property<float>("MaxEu")
                        .HasColumnType("real");

                    b.Property<float>("MaxRaw")
                        .HasColumnType("real");

                    b.Property<float>("MinEu")
                        .HasColumnType("real");

                    b.Property<float>("MinRaw")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceItem")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.TagHistory", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("Number")
                        .HasColumnType("real");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<int>("Using")
                        .HasColumnType("integer");

                    b.ToTable("TagsLive");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.TagHistoryChunk", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Date");

                    b.ToTable("TagHistoryChunks");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.TagInput", b =>
                {
                    b.Property<int>("InputTagId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("TagId");

                    b.ToTable("TagInputs");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<Guid?>("KeycloakGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("StaticHost")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.UserGroup", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.UserGroupRelation", b =>
                {
                    b.Property<Guid>("UserGroupGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessType")
                        .HasColumnType("integer");

                    b.HasKey("UserGroupGuid", "UserGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("UserGroupRelation");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.AccessRights", b =>
                {
                    b.HasOne("DatalakeDatabase.Models.Block", "Block")
                        .WithMany("AccessRightsList")
                        .HasForeignKey("BlockId");

                    b.HasOne("DatalakeDatabase.Models.Source", "Source")
                        .WithMany("AccessRightsList")
                        .HasForeignKey("SourceId");

                    b.HasOne("DatalakeDatabase.Models.Tag", "Tag")
                        .WithMany("AccessRightsList")
                        .HasForeignKey("TagId");

                    b.HasOne("DatalakeDatabase.Models.UserGroup", "UserGroup")
                        .WithMany("AccessRightsList")
                        .HasForeignKey("UserGroupGuid");

                    b.HasOne("DatalakeDatabase.Models.User", "User")
                        .WithMany("AccessRightsList")
                        .HasForeignKey("UserGuid");

                    b.Navigation("Block");

                    b.Navigation("Source");

                    b.Navigation("Tag");

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.BlockProperty", b =>
                {
                    b.HasOne("DatalakeDatabase.Models.Block", "Block")
                        .WithMany("Properties")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.BlockTag", b =>
                {
                    b.HasOne("DatalakeDatabase.Models.Block", "Block")
                        .WithMany("RelationsToTags")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DatalakeDatabase.Models.Tag", "Tag")
                        .WithMany("RelationsToBlocks")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.Tag", b =>
                {
                    b.HasOne("DatalakeDatabase.Models.Source", "Source")
                        .WithMany("Tags")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.TagInput", b =>
                {
                    b.HasOne("DatalakeDatabase.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.UserGroupRelation", b =>
                {
                    b.HasOne("DatalakeDatabase.Models.User", "User")
                        .WithMany("GroupsRelations")
                        .HasForeignKey("UserGroupGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DatalakeDatabase.Models.UserGroup", "UserGroup")
                        .WithMany("UsersRelations")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.Block", b =>
                {
                    b.Navigation("AccessRightsList");

                    b.Navigation("Properties");

                    b.Navigation("RelationsToTags");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.Source", b =>
                {
                    b.Navigation("AccessRightsList");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.Tag", b =>
                {
                    b.Navigation("AccessRightsList");

                    b.Navigation("RelationsToBlocks");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.User", b =>
                {
                    b.Navigation("AccessRightsList");

                    b.Navigation("GroupsRelations");
                });

            modelBuilder.Entity("DatalakeDatabase.Models.UserGroup", b =>
                {
                    b.Navigation("AccessRightsList");

                    b.Navigation("UsersRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
