stages:
  - build
  - push
  - deploy

build-server:
  stage: build

  tags:
    - push-build

  script:
    - docker build -t datalake:latest  -f ./DatalakeServer/Dockerfile .
    - docker tag datalake:latest "$CI_REPOS_URL"/datalake:"$CI_COMMIT_TAG"
    - docker tag datalake:latest "$CI_REPOS_URL"/datalake:latest

  only:
    - /^\d+.\d+.\d+.release$/

push-server:
  stage: push

  tags:
    - push-build

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

  script:
    - docker push "$CI_REPOS_URL"/datalake:"$CI_COMMIT_TAG"
    - docker push "$CI_REPOS_URL"/datalake:latest

  only:
    - /^\d+.\d+.\d+.release$/

deploy-server:
  stage: deploy

  tags:
    - local-ve

  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]

  script:
    - kubectl delete -n sinus pods -l app=datalake

  only:
    - /^\d+.\d+.\d+.release$/