stages:
  - build
  - push
  - deploy

build-server-prod:
  stage: build

  tags:
    - push-build

  script:
    - echo "Building version $VERSION"
    - docker build --build-arg APP_VERSION="$VERSION" -t datalake:latest  -f ./Apps/Server/Dockerfile .
    - docker tag datalake:latest "$CI_REPOS_URL"/datalake:"$CI_COMMIT_TAG"
    - docker tag datalake:latest "$CI_REPOS_URL"/datalake:latest

  only:
    - /^prod\.\d+(\.\d+){0,2}$/

push-server-prod:
  stage: push

  tags:
    - push-build

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

  script:
    - docker push "$CI_REPOS_URL"/datalake:"$CI_COMMIT_TAG"
    - docker push "$CI_REPOS_URL"/datalake:latest

  only:
    - /^prod\.\d+(\.\d+){0,2}$/

deploy-server-prod:
  stage: deploy

  tags:
    - local-ve

  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]

  script:
    - kubectl delete -n sinus pods -l app=datalake

  only:
    - /^prod\.\d+(\.\d+){0,2}$/