stages:
  - build
  - push
  - deploy

build-server:
  stage: build

  tags:
    - push-build

  script:
    - docker build --no-cache -t datalake:latest-test  -f ./Server/Dockerfile .
    - docker tag datalake:latest-test "$CI_REPOS_URL"/datalake:latest-test

  only:
    - /^test.\d+$/

push-server:
  stage: push

  tags:
    - push-build

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

  script:
    - docker push "$CI_REPOS_URL"/datalake:latest-test
 
  only:
    - /^test.\d+$/

deploy-server:
  stage: deploy

  tags:
    - local-ve

  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]

  script:
    - kubectl delete -n sinus-test pods -l app=datalake-test

  only:
    - /^test.\d+$/
